"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def get_env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def get_env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-cf@(&uwoz3q#az+$4@ji^%v@-pg=@=bjqzfvw=6468ogml7fs+',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = get_env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
    'accounts',
    'portfolios',
    'stocks',
    'analysis',
    'recommendations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')),
        'NAME': os.environ.get('DJANGO_DB_NAME', os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DJANGO_DB_USER', os.environ.get('DB_USER', '')),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', os.environ.get('DB_PASSWORD', '')),
        'HOST': os.environ.get('DJANGO_DB_HOST', os.environ.get('DB_HOST', '127.0.0.1')),
        'PORT': os.environ.get('DJANGO_DB_PORT', os.environ.get('DB_PORT', '5432')),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test_db.sqlite3',
    }
    MIGRATION_MODULES = {
        'accounts': None,
        'analysis': None,
        'core': None,
        'portfolios': None,
        'recommendations': None,
        'stocks': None,
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = get_env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5174,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)
CSRF_TRUSTED_ORIGINS = get_env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:5174,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'my-finance-cache',
    }
}

ANALYSIS_CACHE_TTL_SECONDS = 900

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_CHAT_MODEL = os.environ.get('OPENAI_CHAT_MODEL', 'gpt-5-mini')
OPENAI_GUARD_MODEL = os.environ.get('OPENAI_GUARD_MODEL', 'gpt-5-nano')
OPENAI_CHAT_BENCHMARK_MODELS = get_env_list(
    'OPENAI_CHAT_BENCHMARK_MODELS',
    'gpt-5-mini,gpt-5.2,gpt-5-nano',
)
CHATBOT_ALLOWED_ROUTE_PATHS = get_env_list(
    'CHATBOT_ALLOWED_ROUTE_PATHS',
    '/home,/news,/portfolios,/profile',
)
CHATBOT_HISTORY_LIMIT = int(os.environ.get('CHATBOT_HISTORY_LIMIT', 6))
CHATBOT_RETRIEVAL_LIMIT = int(os.environ.get('CHATBOT_RETRIEVAL_LIMIT', 3))
CHATBOT_RECOMMENDATION_CACHE_TTL_SECONDS = int(
    os.environ.get('CHATBOT_RECOMMENDATION_CACHE_TTL_SECONDS', 300)
)
CHATBOT_LOCAL_ONLY = get_env_bool('CHATBOT_LOCAL_ONLY', default=True)
CHATBOT_USE_OLLAMA = get_env_bool('CHATBOT_USE_OLLAMA', default=False)
CHATBOT_OLLAMA_URL = os.environ.get('CHATBOT_OLLAMA_URL', 'http://127.0.0.1:11434/api/generate')
CHATBOT_OLLAMA_MODEL = os.environ.get('CHATBOT_OLLAMA_MODEL', 'qwen2.5:7b')
CHATBOT_USE_FINBERT = get_env_bool('CHATBOT_USE_FINBERT', default=False)
CHATBOT_FINBERT_MODEL = os.environ.get('CHATBOT_FINBERT_MODEL', 'ProsusAI/finbert')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = get_env_bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = get_env_bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
